# Site settings
name: Martin Munárriz
title: Martin Munárriz | Programmer & Sound Designer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://lolimjeff.github.io/
baseurl: ''
email: martinrafael.munarriz@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:martinrafael.munarriz@gmail.com
  - title: github
    url: https://github.com/lolimjeff
  - title: linkedin
    url: https://www.linkedin.com/in/martin-mun%C3%A1rriz/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
